version: '3.4'

services:
  birthdaybot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://*:5001,https://*:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Bn98rnQBS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - WebHookUrl=https://3505-2001-56a-7b63-fe00-9027-5498-93bc-535e.ngrok.io
      - Certificate_CN=45.83.194.53
      - SslCertificatePEM=/botcerts/PUBLIC.pem
      - SslCertificatePFX=/botcerts/PUBLIC.pf
    ports:
      - "5001:5001"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https/:ro
      - ./BirthdayBot/Static:/botcerts:ro