//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayBot.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirthdayBot.BLL.Resources.CommandKeys", typeof(CommandKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actUser.
        /// </summary>
        public static string ActualizeUser {
            get {
                return ResourceManager.GetString("ActualizeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addByChats.
        /// </summary>
        public static string AddByChats {
            get {
                return ResourceManager.GetString("AddByChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adByCont.
        /// </summary>
        public static string AddByContact {
            get {
                return ResourceManager.GetString("AddByContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addNote.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addPeople.
        /// </summary>
        public static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addPersonal.
        /// </summary>
        public static string AddPersonal {
            get {
                return ResourceManager.GetString("AddPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ageConfidentialityChange.
        /// </summary>
        public static string AgeConfidentialityChange {
            get {
                return ResourceManager.GetString("AgeConfidentialityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthDateConfirm.
        /// </summary>
        public static string BirthDateConfirm {
            get {
                return ResourceManager.GetString("BirthDateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthDateReject.
        /// </summary>
        public static string BirthDateReject {
            get {
                return ResourceManager.GetString("BirthDateReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeBirthDate.
        /// </summary>
        public static string ChangeBirthDate {
            get {
                return ResourceManager.GetString("ChangeBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeLocation.
        /// </summary>
        public static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeNoteType.
        /// </summary>
        public static string ChangeNoteType {
            get {
                return ResourceManager.GetString("ChangeNoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeSubsType.
        /// </summary>
        public static string ChangeSubscriptionType {
            get {
                return ResourceManager.GetString("ChangeSubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subPrev.
        /// </summary>
        public static string ChatSubscriptionPreview {
            get {
                return ResourceManager.GetString("ChatSubscriptionPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commonNotificationsSettings.
        /// </summary>
        public static string CommonNotificationsSettings {
            get {
                return ResourceManager.GetString("CommonNotificationsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confidentialitySettings.
        /// </summary>
        public static string ConfidentialitySettings {
            get {
                return ResourceManager.GetString("ConfidentialitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confidentialitySettingsInfo.
        /// </summary>
        public static string ConfidentialitySettingsInfo {
            get {
                return ResourceManager.GetString("ConfidentialitySettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geopositionConfirm.
        /// </summary>
        public static string GeopositionConfirm {
            get {
                return ResourceManager.GetString("GeopositionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geopositionReject.
        /// </summary>
        public static string GeopositionReject {
            get {
                return ResourceManager.GetString("GeopositionReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languageSettings.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languageSettingsChange.
        /// </summary>
        public static string LanguageSettingsChange {
            get {
                return ResourceManager.GetString("LanguageSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noteDateConfirm.
        /// </summary>
        public static string NoteDateConfirm {
            get {
                return ResourceManager.GetString("NoteDateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noteDateReject.
        /// </summary>
        public static string NoteDateReject {
            get {
                return ResourceManager.GetString("NoteDateReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noteRemoveConfirm.
        /// </summary>
        public static string NoteRemoveConfirm {
            get {
                return ResourceManager.GetString("NoteRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notificationsSettingsInfo.
        /// </summary>
        public static string NotificationSettingsInfo {
            get {
                return ResourceManager.GetString("NotificationSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notificationsSettings.
        /// </summary>
        public static string NotificationsSettings {
            get {
                return ResourceManager.GetString("NotificationsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notificationSettingsChange.
        /// </summary>
        public static string NotificationsSettingsChange {
            get {
                return ResourceManager.GetString("NotificationsSettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notTgUser.
        /// </summary>
        public static string NotTelegramUser {
            get {
                return ResourceManager.GetString("NotTelegramUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openChat.
        /// </summary>
        public static string OpenChat {
            get {
                return ResourceManager.GetString("OpenChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openNote.
        /// </summary>
        public static string OpenNote {
            get {
                return ResourceManager.GetString("OpenNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openSubs.
        /// </summary>
        public static string OpenSubscription {
            get {
                return ResourceManager.GetString("OpenSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profileSettings.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profSetInf.
        /// </summary>
        public static string ProfileSettingsInfo {
            get {
                return ResourceManager.GetString("ProfileSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeNote.
        /// </summary>
        public static string RemoveNote {
            get {
                return ResourceManager.GetString("RemoveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeSubs.
        /// </summary>
        public static string RemoveSubscription {
            get {
                return ResourceManager.GetString("RemoveSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strongNotificationsSettings.
        /// </summary>
        public static string StrongNotificationsSettings {
            get {
                return ResourceManager.GetString("StrongNotificationsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subByRefRep.
        /// </summary>
        public static string SubscribeByReferralReply {
            get {
                return ResourceManager.GetString("SubscribeByReferralReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsOnMem.
        /// </summary>
        public static string SubscribeOnMember {
            get {
                return ResourceManager.GetString("SubscribeOnMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subPrevCon.
        /// </summary>
        public static string SubscriptionPreviewConfirm {
            get {
                return ResourceManager.GetString("SubscriptionPreviewConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsRemCon.
        /// </summary>
        public static string SubscriptionRemoveConfirm {
            get {
                return ResourceManager.GetString("SubscriptionRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userSettings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
    }
}
